@jsonType = application/json

### Say Hello
# @name Hello

POST {{api-gateway-url}}/rpc
content-type: {{jsonType}}
Accept: {{jsonType}}

{
    "service": "greater-srv",
    "method": "Greeter.Hello",
    "request": {
        "name": "sumo"
    }
}
