// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/account/proto/profile/profile.proto

package profile

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	user "github.com/xmlking/micro-starter-kit/srv/account/proto/user"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenderType int32

const (
	GenderType_GENDER_TYPE_UNSPECIFIED GenderType = 0
	GenderType_GENDER_TYPE_MALE        GenderType = 1
	GenderType_GENDER_TYPE_FEMALE      GenderType = 2
)

var GenderType_name = map[int32]string{
	0: "GENDER_TYPE_UNSPECIFIED",
	1: "GENDER_TYPE_MALE",
	2: "GENDER_TYPE_FEMALE",
}

var GenderType_value = map[string]int32{
	"GENDER_TYPE_UNSPECIFIED": 0,
	"GENDER_TYPE_MALE":        1,
	"GENDER_TYPE_FEMALE":      2,
}

func (x GenderType) String() string {
	return proto.EnumName(GenderType_name, int32(x))
}

func (GenderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{0}
}

// FIXME: https://github.com/envoyproxy/protoc-gen-validate/issues/223
// Workaround in .override.go
type ListRequest struct {
	Limit                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	UserId               *wrappers.StringValue `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender               *wrappers.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListRequest) GetPage() *wrappers.UInt32Value {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ListRequest) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

type ListResponse struct {
	Results              []*user.Profile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResults() []*user.Profile {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetRequest struct {
	Id     *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tz     *wrappers.StringValue `protobuf:"bytes,3,opt,name=tz,proto3" json:"tz,omitempty"`
	Avatar *wrappers.StringValue `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender *wrappers.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	// GenderType gender = 5; // enum // [(validate.rules).enum.defined_only =
	// true]; // FIXME
	Birthday             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetRequest) GetTz() *wrappers.StringValue {
	if m != nil {
		return m.Tz
	}
	return nil
}

func (m *GetRequest) GetAvatar() *wrappers.StringValue {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *GetRequest) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *GetRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

type GetResponse struct {
	Result               *user.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() *user.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateRequest struct {
	Id     *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tz     *wrappers.StringValue `protobuf:"bytes,3,opt,name=tz,proto3" json:"tz,omitempty"`
	Avatar *wrappers.StringValue `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender *wrappers.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	// GenderType gender = 5; // enum // [(validate.rules).enum.defined_only =
	// true]; // FIXME
	Birthday             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *CreateRequest) GetTz() *wrappers.StringValue {
	if m != nil {
		return m.Tz
	}
	return nil
}

func (m *CreateRequest) GetAvatar() *wrappers.StringValue {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *CreateRequest) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *CreateRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

type CreateResponse struct {
	Result               *user.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66f8539c87eeb2a7, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() *user.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("micro.profile.v1.GenderType", GenderType_name, GenderType_value)
	proto.RegisterType((*ListRequest)(nil), "micro.profile.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "micro.profile.v1.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "micro.profile.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "micro.profile.v1.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "micro.profile.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "micro.profile.v1.CreateResponse")
}

func init() {
	proto.RegisterFile("srv/account/proto/profile/profile.proto", fileDescriptor_66f8539c87eeb2a7)
}

var fileDescriptor_66f8539c87eeb2a7 = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xed, 0x38, 0x89, 0xdb, 0x6f, 0xf2, 0xb5, 0x8a, 0x46, 0x55, 0xb1, 0x42, 0xff, 0xc8, 0x86,
	0x50, 0x51, 0x87, 0xa6, 0x12, 0x02, 0x24, 0x0a, 0x75, 0xeb, 0x46, 0x91, 0xda, 0x2a, 0x72, 0x53,
	0x10, 0xb0, 0x88, 0x26, 0xf1, 0x34, 0x1d, 0xd5, 0x89, 0xcd, 0xf8, 0x3a, 0xd0, 0x3e, 0x05, 0x8f,
	0x82, 0xd8, 0xf3, 0x4a, 0xac, 0xab, 0xb0, 0x41, 0xf6, 0xd8, 0x21, 0x34, 0x58, 0x94, 0x1f, 0xb1,
	0x62, 0xe3, 0xc4, 0xf7, 0x9e, 0x73, 0xe7, 0xde, 0x73, 0xc6, 0x33, 0xf8, 0xb6, 0x2f, 0x06, 0x15,
	0xda, 0xe9, 0xb8, 0x41, 0x1f, 0x2a, 0x9e, 0x70, 0xc1, 0x0d, 0x9f, 0x27, 0xdc, 0x61, 0xc9, 0xaf,
	0x1e, 0x45, 0x49, 0xa1, 0xc7, 0x3b, 0xc2, 0xd5, 0x93, 0xe0, 0x60, 0xa3, 0xb8, 0xdc, 0x75, 0xdd,
	0xae, 0xc4, 0x81, 0xdb, 0x0e, 0x4e, 0x2a, 0x6f, 0x04, 0xf5, 0x3c, 0x26, 0x7c, 0xc9, 0x28, 0xae,
	0x5c, 0xcd, 0x03, 0xef, 0x31, 0x1f, 0x68, 0xcf, 0x8b, 0x01, 0x77, 0xe0, 0x94, 0x0b, 0xbb, 0xe5,
	0x51, 0x01, 0xe7, 0xf1, 0xda, 0x03, 0xea, 0x70, 0x9b, 0x02, 0x1b, 0xfd, 0x89, 0xa1, 0xb7, 0x26,
	0xdb, 0x0c, 0x7c, 0x26, 0xa2, 0x87, 0x84, 0x94, 0x3e, 0x2a, 0x38, 0xbf, 0xcf, 0x7d, 0xb0, 0xd8,
	0xeb, 0x80, 0xf9, 0x40, 0x1e, 0xe3, 0x9c, 0xc3, 0x7b, 0x1c, 0x34, 0xb4, 0x8a, 0xca, 0xf9, 0xea,
	0xa2, 0x2e, 0xdb, 0xd1, 0x93, 0x76, 0xf4, 0xe3, 0x7a, 0x1f, 0x36, 0xab, 0xcf, 0xa8, 0x13, 0x30,
	0xe3, 0xbf, 0xa1, 0xa1, 0xae, 0x65, 0x35, 0xbb, 0x8c, 0x2c, 0xc9, 0x22, 0x0f, 0x71, 0xd6, 0xa3,
	0x5d, 0xa6, 0x29, 0xd7, 0x60, 0x4f, 0x0f, 0x8d, 0xec, 0x9a, 0x52, 0x46, 0x56, 0x44, 0x21, 0xf7,
	0x70, 0xd6, 0x77, 0x05, 0x68, 0x99, 0x14, 0xea, 0x11, 0x08, 0xde, 0xef, 0x46, 0x54, 0x2b, 0x42,
	0x92, 0x27, 0x78, 0x3a, 0x9c, 0xa4, 0xc5, 0x6d, 0x2d, 0xfb, 0x63, 0x92, 0x31, 0x33, 0x34, 0x72,
	0x22, 0xf3, 0x1e, 0x21, 0x4b, 0x0d, 0x69, 0x75, 0x9b, 0x6c, 0x63, 0xb5, 0xcb, 0xfa, 0x36, 0x13,
	0x5a, 0xee, 0x1a, 0xfc, 0xfc, 0xd0, 0x98, 0x11, 0xaa, 0x85, 0x0e, 0x2c, 0xb4, 0x67, 0xc5, 0xc4,
	0xd2, 0x2b, 0xfc, 0xbf, 0x94, 0xcf, 0xf7, 0xdc, 0xbe, 0x1f, 0x4e, 0x31, 0x2d, 0x98, 0x1f, 0x38,
	0xe0, 0x6b, 0x68, 0x35, 0x53, 0xce, 0x57, 0x17, 0x74, 0xb9, 0x05, 0x22, 0xcd, 0x07, 0x1b, 0x7a,
	0x43, 0x6e, 0x05, 0x2b, 0x81, 0x91, 0x79, 0x9c, 0x03, 0x17, 0xa8, 0x13, 0x69, 0x36, 0x6b, 0xc9,
	0x97, 0x47, 0x99, 0x4b, 0x03, 0x95, 0x2e, 0x15, 0x8c, 0x6b, 0x6c, 0xe4, 0xcd, 0x7d, 0xac, 0x70,
	0x3b, 0xd5, 0x98, 0xef, 0x8f, 0xaa, 0x70, 0x7b, 0x5c, 0x27, 0xe5, 0x97, 0x74, 0xba, 0x8b, 0x15,
	0xb8, 0xb8, 0x96, 0x31, 0x0a, 0x5c, 0x90, 0x2d, 0xac, 0xd2, 0x01, 0x05, 0x2a, 0x7e, 0xc2, 0x95,
	0x77, 0xe1, 0x6a, 0x92, 0xf5, 0x07, 0x5c, 0x21, 0x4f, 0xf1, 0x4c, 0x9b, 0x0b, 0x38, 0xb5, 0xe9,
	0xb9, 0xa6, 0x46, 0x45, 0x8a, 0x13, 0x45, 0x9a, 0xc9, 0x77, 0x15, 0xb5, 0xf0, 0x01, 0x29, 0x0f,
	0x90, 0x35, 0x62, 0x95, 0x0c, 0x9c, 0x8f, 0x94, 0x8f, 0x6d, 0xd5, 0xb1, 0x2a, 0xfd, 0x8a, 0xe5,
	0x4f, 0x73, 0x35, 0x46, 0x49, 0xfb, 0x3e, 0x2b, 0x78, 0x76, 0x47, 0x30, 0x0a, 0xec, 0x9f, 0x83,
	0x7f, 0xdf, 0x41, 0x13, 0xcf, 0x25, 0xe2, 0xff, 0x86, 0x89, 0x6b, 0xcf, 0xc3, 0x4f, 0x30, 0x6c,
	0xa9, 0x79, 0xee, 0x31, 0x72, 0x13, 0xdf, 0xa8, 0x99, 0x87, 0xbb, 0xa6, 0xd5, 0x6a, 0xbe, 0x68,
	0x98, 0xad, 0xe3, 0xc3, 0xa3, 0x86, 0xb9, 0x53, 0xdf, 0xab, 0x9b, 0xbb, 0x85, 0x29, 0x32, 0x8f,
	0x0b, 0xe3, 0xc9, 0x83, 0xed, 0x7d, 0xb3, 0x80, 0xc8, 0x02, 0x26, 0xe3, 0xd1, 0x3d, 0x33, 0x8a,
	0x2b, 0xd5, 0x4f, 0x08, 0xcf, 0xc5, 0x2b, 0x1e, 0x31, 0x31, 0xe0, 0x1d, 0x46, 0x6a, 0x38, 0x1b,
	0x1e, 0x26, 0x64, 0x49, 0xbf, 0x7a, 0x6d, 0xe8, 0x63, 0x67, 0x74, 0x71, 0x39, 0x2d, 0x2d, 0xe7,
	0x2c, 0x4d, 0x91, 0x5d, 0x9c, 0xa9, 0x31, 0x20, 0x8b, 0x93, 0xc0, 0xaf, 0xc7, 0x49, 0x71, 0x29,
	0x25, 0x3b, 0xaa, 0x72, 0x80, 0x55, 0xa9, 0x20, 0x59, 0x99, 0x84, 0x7e, 0xb3, 0xb1, 0x8b, 0xab,
	0xe9, 0x80, 0xa4, 0x9c, 0xd1, 0xc4, 0x13, 0xb7, 0x61, 0x03, 0xbd, 0xdc, 0xea, 0x72, 0x38, 0x0d,
	0xda, 0x7a, 0xc7, 0xed, 0x55, 0xde, 0xf6, 0x9c, 0x33, 0xde, 0xef, 0x56, 0x22, 0xd8, 0xba, 0x0f,
	0x54, 0x00, 0x13, 0xeb, 0x67, 0x1c, 0x2a, 0xa9, 0xf7, 0x6d, 0x5b, 0x8d, 0x5e, 0x37, 0xbf, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xc5, 0xf2, 0x82, 0xe5, 0x93, 0x07, 0x00, 0x00,
}
