// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/account/proto/profile/profile_service.proto

package profile

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	entities "github.com/xmlking/micro-starter-kit/srv/account/proto/entities"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FIXME: https://github.com/envoyproxy/protoc-gen-validate/issues/223
// Workaround in .override.go
type ListRequest struct {
	Limit                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	UserId               *wrappers.StringValue `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender               *wrappers.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListRequest) GetPage() *wrappers.UInt32Value {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ListRequest) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

type ListResponse struct {
	Results              []*entities.Profile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total                uint32              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResults() []*entities.Profile {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetRequest struct {
	// Types that are valid to be assigned to Id:
	//	*GetRequest_ProfileId
	//	*GetRequest_UserId
	Id                   isGetRequest_Id `protobuf_oneof:"id"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type isGetRequest_Id interface {
	isGetRequest_Id()
}

type GetRequest_ProfileId struct {
	ProfileId *wrappers.StringValue `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3,oneof"`
}

type GetRequest_UserId struct {
	UserId *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*GetRequest_ProfileId) isGetRequest_Id() {}

func (*GetRequest_UserId) isGetRequest_Id() {}

func (m *GetRequest) GetId() isGetRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetRequest) GetProfileId() *wrappers.StringValue {
	if x, ok := m.GetId().(*GetRequest_ProfileId); ok {
		return x.ProfileId
	}
	return nil
}

func (m *GetRequest) GetUserId() *wrappers.StringValue {
	if x, ok := m.GetId().(*GetRequest_UserId); ok {
		return x.UserId
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetRequest_ProfileId)(nil),
		(*GetRequest_UserId)(nil),
	}
}

type GetResponse struct {
	Result               *entities.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{3}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() *entities.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateRequest struct {
	Id     *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId *wrappers.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tz     *wrappers.StringValue `protobuf:"bytes,3,opt,name=tz,proto3" json:"tz,omitempty"`
	Avatar *wrappers.StringValue `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender *wrappers.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	// GenderType gender = 5; // enum // [(validate.rules).enum.defined_only =
	// true]; // FIXME
	Birthday             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateRequest) GetUserId() *wrappers.StringValue {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *CreateRequest) GetTz() *wrappers.StringValue {
	if m != nil {
		return m.Tz
	}
	return nil
}

func (m *CreateRequest) GetAvatar() *wrappers.StringValue {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *CreateRequest) GetGender() *wrappers.StringValue {
	if m != nil {
		return m.Gender
	}
	return nil
}

func (m *CreateRequest) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

type CreateResponse struct {
	Result               *entities.Profile `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb9861f269b0aad5, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() *entities.Profile {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "micro.account.profile.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "micro.account.profile.v1.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "micro.account.profile.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "micro.account.profile.v1.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "micro.account.profile.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "micro.account.profile.v1.CreateResponse")
}

func init() {
	proto.RegisterFile("srv/account/proto/profile/profile_service.proto", fileDescriptor_cb9861f269b0aad5)
}

var fileDescriptor_cb9861f269b0aad5 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x86, 0xef, 0x38, 0x89, 0xdb, 0x9e, 0xdc, 0x76, 0x31, 0xba, 0x0b, 0x2b, 0xba, 0x82, 0x2a,
	0xa2, 0x10, 0x2a, 0xea, 0xd0, 0x54, 0x42, 0x50, 0x41, 0x01, 0x23, 0x51, 0x2a, 0x01, 0x2a, 0x53,
	0xca, 0x02, 0x90, 0xaa, 0x49, 0x3c, 0x75, 0x47, 0x75, 0x6c, 0x33, 0x73, 0x1c, 0x68, 0x9f, 0x82,
	0x25, 0x2b, 0x9e, 0x01, 0xb1, 0xe7, 0xbd, 0x50, 0xd8, 0xa0, 0x78, 0xec, 0xd0, 0x52, 0xac, 0xa4,
	0xa8, 0x9b, 0xc4, 0xd6, 0xfc, 0xdf, 0xf1, 0x39, 0xff, 0xfc, 0x1e, 0x43, 0x5b, 0xab, 0x41, 0x9b,
	0xf7, 0x7a, 0x71, 0x1a, 0x61, 0x3b, 0x51, 0x31, 0xc6, 0xa3, 0xdf, 0x7d, 0x19, 0x8a, 0xe2, 0x7f,
	0x4f, 0x0b, 0x35, 0x90, 0x3d, 0xe1, 0x66, 0xab, 0xd4, 0xe9, 0xcb, 0x9e, 0x8a, 0xdd, 0x1c, 0x71,
	0x73, 0x91, 0x3b, 0x58, 0x6d, 0x5c, 0x0e, 0xe2, 0x38, 0x30, 0x1c, 0xc6, 0xdd, 0x74, 0xbf, 0x8d,
	0xb2, 0x2f, 0x34, 0xf2, 0x7e, 0x62, 0xd0, 0xc6, 0xa5, 0xdf, 0x05, 0xef, 0x15, 0x4f, 0x12, 0xa1,
	0x74, 0xbe, 0x7e, 0xfd, 0x6c, 0x2f, 0x22, 0x42, 0x89, 0x52, 0xe8, 0xf1, 0x45, 0x21, 0xc5, 0x03,
	0xa9, 0xfc, 0xbd, 0x84, 0x2b, 0x3c, 0xca, 0xa5, 0x03, 0x1e, 0x4a, 0x9f, 0xa3, 0x18, 0x5f, 0x18,
	0x69, 0xf3, 0x9b, 0x05, 0xf5, 0xa7, 0x52, 0x23, 0x13, 0xef, 0x52, 0xa1, 0x91, 0xde, 0x83, 0x5a,
	0x28, 0xfb, 0x12, 0x1d, 0xb2, 0x48, 0x5a, 0xf5, 0xce, 0xff, 0xae, 0xe9, 0xca, 0x2d, 0xba, 0x72,
	0x77, 0xb7, 0x22, 0x5c, 0xeb, 0xbc, 0xe2, 0x61, 0x2a, 0xbc, 0xb9, 0xa1, 0x67, 0x2f, 0x57, 0x1d,
	0xbf, 0x45, 0x98, 0xa1, 0xe8, 0x1d, 0xa8, 0x26, 0x3c, 0x10, 0x8e, 0x35, 0x05, 0x3d, 0x33, 0xf4,
	0xaa, 0xcb, 0x56, 0x8b, 0xb0, 0x0c, 0xa1, 0x37, 0xa1, 0xaa, 0x63, 0x85, 0x4e, 0xa5, 0x04, 0xdd,
	0x41, 0x25, 0xa3, 0x20, 0x43, 0x59, 0xa6, 0xa4, 0xf7, 0x61, 0x26, 0xd5, 0x42, 0xed, 0x49, 0xdf,
	0xa9, 0x4e, 0x86, 0xbc, 0xd9, 0xa1, 0x57, 0x53, 0x95, 0x2f, 0x84, 0x30, 0x7b, 0x84, 0x6d, 0xf9,
	0xf4, 0x21, 0xd8, 0x81, 0x88, 0x7c, 0xa1, 0x9c, 0xda, 0x14, 0x7c, 0x7d, 0xe8, 0xcd, 0x2a, 0x9b,
	0x91, 0x67, 0x8c, 0x3c, 0x66, 0x39, 0xd8, 0x0c, 0xe0, 0x5f, 0x63, 0x9f, 0x4e, 0xe2, 0x48, 0x0b,
	0x7a, 0x17, 0x66, 0x94, 0xd0, 0x69, 0x88, 0xda, 0x21, 0x8b, 0x95, 0x56, 0xbd, 0xd3, 0x74, 0x4f,
	0x47, 0x62, 0xbc, 0x55, 0x83, 0x55, 0x77, 0xdb, 0xc4, 0x83, 0x15, 0x08, 0xfd, 0x0f, 0x6a, 0x18,
	0x23, 0x0f, 0x33, 0xff, 0xe6, 0x99, 0xb9, 0x59, 0xaf, 0x7c, 0xf7, 0x48, 0xf3, 0x33, 0x01, 0xd8,
	0x14, 0xe3, 0x7d, 0xda, 0x04, 0x28, 0x12, 0x28, 0xfd, 0xd2, 0xcd, 0xfa, 0xe3, 0xf8, 0x4f, 0xfe,
	0x61, 0x73, 0x39, 0x9b, 0x79, 0x30, 0x36, 0xd1, 0x3a, 0x67, 0x95, 0xdc, 0x46, 0xaf, 0x0a, 0x96,
	0xf4, 0x9b, 0xcf, 0xa1, 0x9e, 0xf5, 0x97, 0x1b, 0xb1, 0x0e, 0xb6, 0x99, 0x2a, 0x6f, 0x6e, 0x1a,
	0x1f, 0x72, 0xc2, 0x0c, 0xfc, 0xc3, 0x82, 0xf9, 0x47, 0x4a, 0x70, 0x14, 0xc5, 0xcc, 0xb7, 0x46,
	0xcf, 0x39, 0xdf, 0xac, 0xcc, 0x92, 0xfe, 0xc9, 0x9c, 0x58, 0x7f, 0x95, 0x93, 0x1b, 0x60, 0xe1,
	0xf1, 0x54, 0xc1, 0xb4, 0xf0, 0x98, 0x6e, 0x80, 0xcd, 0x07, 0x1c, 0xb9, 0x3a, 0x47, 0x2a, 0x3f,
	0x8e, 0x9e, 0x66, 0xa8, 0x0b, 0x48, 0x25, 0x7d, 0x00, 0xb3, 0x5d, 0xa9, 0xf0, 0xc0, 0xe7, 0x47,
	0x8e, 0x9d, 0x15, 0x69, 0x9c, 0x29, 0xf2, 0xb2, 0x38, 0x7f, 0xb2, 0x16, 0xbe, 0x12, 0xeb, 0x36,
	0x61, 0x63, 0xaa, 0xf9, 0x02, 0x16, 0x0a, 0xf3, 0x2f, 0x68, 0x43, 0x3b, 0x9f, 0x2c, 0x58, 0xc8,
	0x17, 0x76, 0xcc, 0xa1, 0x49, 0x77, 0xa1, 0x3a, 0x7a, 0x7b, 0xe8, 0x92, 0x5b, 0x76, 0x6e, 0xba,
	0x27, 0x0e, 0xa7, 0xc6, 0xd5, 0x49, 0xb2, 0xbc, 0x55, 0x06, 0x95, 0x4d, 0x81, 0xf4, 0x4a, 0xb9,
	0xfc, 0xd7, 0x9b, 0xd4, 0x58, 0x9a, 0xa0, 0xca, 0x6b, 0xbe, 0x01, 0xdb, 0x18, 0x42, 0xaf, 0x95,
	0x03, 0xa7, 0xf2, 0xda, 0x68, 0x4d, 0x16, 0x9a, 0xe2, 0xde, 0x5b, 0x28, 0xfd, 0x70, 0x6c, 0x93,
	0xd7, 0x1b, 0x81, 0xc4, 0x83, 0xb4, 0xeb, 0xf6, 0xe2, 0x7e, 0xfb, 0x43, 0x3f, 0x3c, 0x94, 0x51,
	0xd0, 0xce, 0xe4, 0x2b, 0x1a, 0xb9, 0x42, 0xa1, 0x56, 0x0e, 0x25, 0x96, 0x7f, 0xaa, 0xba, 0x76,
	0x76, 0xbb, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x78, 0x86, 0xd7, 0x80, 0xce, 0x06, 0x00, 0x00,
}
