// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/account/proto/user/user_service.proto

package user

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	entities "github.com/xmlking/micro-starter-kit/service/account/proto/entities"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FIXME: https://github.com/envoyproxy/protoc-gen-validate/issues/223
// with Workaround in .override.go
type ExistRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExistRequest) Reset()         { *m = ExistRequest{} }
func (m *ExistRequest) String() string { return proto.CompactTextString(m) }
func (*ExistRequest) ProtoMessage()    {}
func (*ExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{0}
}

func (m *ExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRequest.Unmarshal(m, b)
}
func (m *ExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRequest.Marshal(b, m, deterministic)
}
func (m *ExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRequest.Merge(m, src)
}
func (m *ExistRequest) XXX_Size() int {
	return xxx_messageInfo_ExistRequest.Size(m)
}
func (m *ExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRequest proto.InternalMessageInfo

func (m *ExistRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ExistRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ExistRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *ExistRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *ExistRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type ExistResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistResponse) Reset()         { *m = ExistResponse{} }
func (m *ExistResponse) String() string { return proto.CompactTextString(m) }
func (*ExistResponse) ProtoMessage()    {}
func (*ExistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{1}
}

func (m *ExistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistResponse.Unmarshal(m, b)
}
func (m *ExistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistResponse.Marshal(b, m, deterministic)
}
func (m *ExistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistResponse.Merge(m, src)
}
func (m *ExistResponse) XXX_Size() int {
	return xxx_messageInfo_ExistResponse.Size(m)
}
func (m *ExistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExistResponse proto.InternalMessageInfo

func (m *ExistResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type ListRequest struct {
	Limit                *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Sort                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ListRequest) GetPage() *wrappers.UInt32Value {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *ListRequest) GetSort() *wrappers.StringValue {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ListRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *ListRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *ListRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *ListRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type ListResponse struct {
	Results              []*entities.User `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total                uint32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResults() []*entities.User {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *GetRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *GetRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *GetRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type GetResponse struct {
	Result               *entities.User `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() *entities.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateRequest struct {
	Username             *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{6}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *CreateRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *CreateRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *CreateRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type CreateResponse struct {
	Result               *entities.User `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{7}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetResult() *entities.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *UpdateRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *UpdateRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *UpdateRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type UpdateResponse struct {
	Result               *entities.User `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() *entities.User {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            *wrappers.StringValue `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             *wrappers.StringValue `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{10}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DeleteRequest) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *DeleteRequest) GetFirstName() *wrappers.StringValue {
	if m != nil {
		return m.FirstName
	}
	return nil
}

func (m *DeleteRequest) GetLastName() *wrappers.StringValue {
	if m != nil {
		return m.LastName
	}
	return nil
}

func (m *DeleteRequest) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

type DeleteResponse struct {
	Result               *entities.User `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22c3487ee047ec58, []int{11}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetResult() *entities.User {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*ExistRequest)(nil), "mkit.service.account.user.v1.ExistRequest")
	proto.RegisterType((*ExistResponse)(nil), "mkit.service.account.user.v1.ExistResponse")
	proto.RegisterType((*ListRequest)(nil), "mkit.service.account.user.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "mkit.service.account.user.v1.ListResponse")
	proto.RegisterType((*GetRequest)(nil), "mkit.service.account.user.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "mkit.service.account.user.v1.GetResponse")
	proto.RegisterType((*CreateRequest)(nil), "mkit.service.account.user.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "mkit.service.account.user.v1.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "mkit.service.account.user.v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "mkit.service.account.user.v1.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "mkit.service.account.user.v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "mkit.service.account.user.v1.DeleteResponse")
}

func init() {
	proto.RegisterFile("service/account/proto/user/user_service.proto", fileDescriptor_22c3487ee047ec58)
}

var fileDescriptor_22c3487ee047ec58 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdf, 0x6b, 0x13, 0x4b,
	0x14, 0x66, 0x37, 0x9b, 0x34, 0x3d, 0x69, 0x2e, 0x65, 0xb8, 0x5c, 0x42, 0x6e, 0xef, 0xa5, 0x14,
	0x91, 0x34, 0x36, 0x9b, 0x36, 0x45, 0xa1, 0x8a, 0x3f, 0x58, 0x2b, 0x45, 0x28, 0x22, 0x5b, 0xe2,
	0x43, 0xa5, 0xa6, 0xd3, 0x64, 0x9a, 0x0e, 0xd9, 0x5f, 0xce, 0xcc, 0xc6, 0xaa, 0x08, 0xfe, 0x49,
	0xe2, 0x7f, 0x23, 0xf8, 0x2e, 0xfa, 0x17, 0x48, 0x9e, 0x64, 0x77, 0x76, 0xd3, 0xac, 0x98, 0x64,
	0xd5, 0xd4, 0xa7, 0xbc, 0x84, 0xd9, 0xc9, 0xf9, 0xbe, 0x33, 0x7b, 0xbe, 0xef, 0xcc, 0xcc, 0x42,
	0x8d, 0x13, 0xd6, 0xa7, 0x6d, 0x52, 0xc7, 0xed, 0xb6, 0xeb, 0x3b, 0xa2, 0xee, 0x31, 0x57, 0xb8,
	0x75, 0x9f, 0x13, 0x16, 0xfe, 0xb4, 0xa2, 0xff, 0xf5, 0x70, 0x1e, 0xad, 0xd8, 0x3d, 0x2a, 0xf4,
	0x78, 0x2e, 0xc2, 0xe8, 0x41, 0xa0, 0xde, 0xdf, 0x2a, 0xff, 0xdf, 0x75, 0xdd, 0xae, 0x45, 0x24,
	0xc7, 0x89, 0x7f, 0x5a, 0x7f, 0xc1, 0xb0, 0xe7, 0x11, 0xc6, 0x25, 0xba, 0x3c, 0x26, 0x19, 0x71,
	0x04, 0x15, 0x94, 0xf0, 0xe1, 0x20, 0x0a, 0x5f, 0x17, 0x67, 0x94, 0x75, 0x5a, 0x1e, 0x66, 0xe2,
	0x65, 0x14, 0xda, 0xc7, 0x16, 0xed, 0x60, 0x41, 0x86, 0x03, 0x19, 0xba, 0xf6, 0x59, 0x85, 0xa5,
	0x07, 0xe7, 0x94, 0x0b, 0x93, 0x3c, 0xf7, 0x09, 0x17, 0xe8, 0x06, 0xa8, 0xb4, 0x53, 0x52, 0x56,
	0x95, 0x4a, 0xa1, 0xb1, 0xa2, 0xcb, 0x75, 0xe9, 0xf1, 0xba, 0xf4, 0x03, 0xc1, 0xa8, 0xd3, 0x7d,
	0x82, 0x2d, 0x9f, 0x18, 0xf9, 0x81, 0x91, 0x65, 0x99, 0x77, 0x8a, 0x62, 0xaa, 0xb4, 0x83, 0x0e,
	0x21, 0x1f, 0xbc, 0x8d, 0x83, 0x6d, 0x52, 0x52, 0x53, 0xa0, 0x57, 0x07, 0xc6, 0x7f, 0xec, 0xdf,
	0x65, 0xad, 0xb4, 0x5c, 0x79, 0xab, 0x36, 0xd0, 0xb3, 0xa7, 0xb8, 0xf6, 0x6a, 0xb3, 0xb6, 0xd3,
	0xaa, 0x1d, 0xbd, 0xde, 0xde, 0xd8, 0xba, 0xfe, 0xe6, 0x8a, 0x39, 0xe4, 0x43, 0xbb, 0x00, 0xa7,
	0x94, 0x71, 0xd1, 0x0a, 0xd9, 0x33, 0x29, 0xd8, 0x17, 0x06, 0x86, 0xc6, 0xd4, 0xe5, 0x8c, 0xb9,
	0x18, 0x02, 0x1f, 0x05, 0x2c, 0x06, 0x2c, 0x5a, 0x38, 0x26, 0xd1, 0x7e, 0x86, 0x24, 0x1f, 0xe0,
	0x42, 0x8e, 0x5b, 0x90, 0x25, 0x36, 0xa6, 0x56, 0x29, 0x9b, 0x1a, 0x7f, 0xac, 0x98, 0x12, 0xb3,
	0xb6, 0x01, 0xc5, 0xa8, 0xd4, 0xdc, 0x73, 0x1d, 0x4e, 0xd0, 0x3f, 0x90, 0x63, 0x84, 0xfb, 0x96,
	0x08, 0xeb, 0x9d, 0x37, 0xa3, 0xa7, 0x9b, 0x99, 0xaf, 0x86, 0xb2, 0xf6, 0x31, 0x03, 0x85, 0xfd,
	0x11, 0x61, 0x6e, 0x43, 0xd6, 0xa2, 0x36, 0x15, 0x63, 0xb5, 0x69, 0x3e, 0x74, 0xc4, 0x76, 0x43,
	0xa6, 0x5e, 0x1c, 0x18, 0xb9, 0xaa, 0x56, 0xea, 0x54, 0x14, 0x53, 0xa2, 0xd0, 0x0e, 0x68, 0x1e,
	0xee, 0x8e, 0xd7, 0x66, 0x14, 0x1d, 0x2c, 0xbc, 0xaa, 0x56, 0x14, 0x33, 0x84, 0xa0, 0x4d, 0xd0,
	0xb8, 0xcb, 0x44, 0x9a, 0xc2, 0x9b, 0x61, 0x64, 0xc2, 0x0c, 0xda, 0xa5, 0x9a, 0x21, 0x3b, 0x0b,
	0x33, 0xe4, 0x7e, 0xd3, 0x0c, 0x0b, 0xbf, 0x60, 0x86, 0x1e, 0x2c, 0xed, 0x8f, 0x7a, 0xe1, 0x1e,
	0x2c, 0x48, 0xf5, 0x79, 0x49, 0x59, 0xcd, 0x54, 0x0a, 0x8d, 0xab, 0xfa, 0x0f, 0xb7, 0x8c, 0x61,
	0xab, 0xf7, 0xb7, 0xf4, 0x26, 0x27, 0xcc, 0x8c, 0x61, 0xe8, 0x6f, 0xc8, 0x0a, 0x57, 0x60, 0x2b,
	0x94, 0xb8, 0x68, 0xca, 0x07, 0xe9, 0xa5, 0x4f, 0x2a, 0xc0, 0x1e, 0x99, 0xf7, 0xf8, 0xe5, 0xf7,
	0xb8, 0x09, 0x85, 0xb0, 0xd0, 0x91, 0xaa, 0x77, 0x12, 0x1d, 0x9e, 0x5e, 0xd4, 0xc4, 0x4e, 0xf0,
	0x5e, 0x85, 0xe2, 0x7d, 0x46, 0xb0, 0x20, 0xb1, 0x80, 0x73, 0x21, 0xa6, 0x0a, 0xd1, 0x84, 0xbf,
	0xe2, 0x9a, 0xcd, 0x52, 0x8b, 0x2f, 0x2a, 0x14, 0x9b, 0x5e, 0x67, 0x44, 0x8b, 0x79, 0x33, 0x5d,
	0xa6, 0x86, 0x71, 0xad, 0x67, 0xad, 0xe1, 0x2e, 0xb1, 0xc8, 0x5c, 0xc3, 0x3f, 0xa3, 0x61, 0x5c,
	0xeb, 0x19, 0x6a, 0xd8, 0xf8, 0xa0, 0x41, 0x21, 0x98, 0x3d, 0x90, 0x28, 0x74, 0x0c, 0xd9, 0xf0,
	0x6e, 0x85, 0xaa, 0xfa, 0xa4, 0x9b, 0xb6, 0x3e, 0x7a, 0xd7, 0x2d, 0x5f, 0x4b, 0x15, 0x1b, 0x2d,
	0xfb, 0x08, 0xb4, 0xe0, 0xc0, 0x46, 0xeb, 0x93, 0x41, 0x23, 0x57, 0xb6, 0x72, 0x35, 0x4d, 0x68,
	0x44, 0x7f, 0x08, 0x99, 0x3d, 0x22, 0x50, 0x65, 0x32, 0xe4, 0xe2, 0x10, 0x2f, 0xaf, 0xa7, 0x88,
	0x8c, 0xb8, 0xdb, 0x90, 0x93, 0x7b, 0x21, 0x9a, 0xf2, 0xc6, 0x89, 0x53, 0xa6, 0xbc, 0x91, 0x2e,
	0xf8, 0x22, 0x89, 0x6c, 0xd6, 0x69, 0x49, 0x12, 0xdb, 0xe7, 0xb4, 0x24, 0xdf, 0xf5, 0x7f, 0x1b,
	0x72, 0xd2, 0x4d, 0xd3, 0x92, 0x24, 0xfa, 0x7b, 0x5a, 0x92, 0xa4, 0x41, 0x0d, 0x0c, 0x13, 0xbf,
	0xd6, 0x1e, 0x2b, 0x87, 0x77, 0xbb, 0x54, 0x9c, 0xf9, 0x27, 0x7a, 0xdb, 0xb5, 0xeb, 0xe7, 0xb6,
	0xd5, 0xa3, 0x4e, 0xb7, 0x6e, 0xd3, 0x36, 0x73, 0x6b, 0x5c, 0x60, 0x26, 0x08, 0xab, 0xf5, 0xa8,
	0xa8, 0x8f, 0xff, 0x42, 0x3c, 0xc9, 0x85, 0xe3, 0xed, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8,
	0x75, 0x31, 0xcd, 0x46, 0x0e, 0x00, 0x00,
}
