// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/recorder/proto/recorder/recorder.proto

package recordersrv

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReadRequest) Reset()         { *m = TransactionReadRequest{} }
func (m *TransactionReadRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionReadRequest) ProtoMessage()    {}
func (*TransactionReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65991f949dbc3f7a, []int{0}
}

func (m *TransactionReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReadRequest.Unmarshal(m, b)
}
func (m *TransactionReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReadRequest.Marshal(b, m, deterministic)
}
func (m *TransactionReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReadRequest.Merge(m, src)
}
func (m *TransactionReadRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionReadRequest.Size(m)
}
func (m *TransactionReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReadRequest proto.InternalMessageInfo

func (m *TransactionReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TransactionWriteRequest struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Event                *TransactionEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionWriteRequest) Reset()         { *m = TransactionWriteRequest{} }
func (m *TransactionWriteRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionWriteRequest) ProtoMessage()    {}
func (*TransactionWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65991f949dbc3f7a, []int{1}
}

func (m *TransactionWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWriteRequest.Unmarshal(m, b)
}
func (m *TransactionWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWriteRequest.Marshal(b, m, deterministic)
}
func (m *TransactionWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWriteRequest.Merge(m, src)
}
func (m *TransactionWriteRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionWriteRequest.Size(m)
}
func (m *TransactionWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWriteRequest proto.InternalMessageInfo

func (m *TransactionWriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TransactionWriteRequest) GetEvent() *TransactionEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

// Transaction Event
type TransactionEvent struct {
	// request
	Req []byte `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	// responce
	Rsp                  []byte   `protobuf:"bytes,2,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_65991f949dbc3f7a, []int{2}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *TransactionEvent) GetRsp() []byte {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionReadRequest)(nil), "recordersrv.TransactionReadRequest")
	proto.RegisterType((*TransactionWriteRequest)(nil), "recordersrv.TransactionWriteRequest")
	proto.RegisterType((*TransactionEvent)(nil), "recordersrv.TransactionEvent")
}

func init() {
	proto.RegisterFile("srv/recorder/proto/recorder/recorder.proto", fileDescriptor_65991f949dbc3f7a)
}

var fileDescriptor_65991f949dbc3f7a = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x6c, 0xac, 0x15, 0xdc, 0x78, 0x28, 0x7b, 0xa8, 0x25, 0x22, 0x94, 0xe8, 0xa1, 0x08, 0xdd,
	0x85, 0x16, 0x3c, 0x78, 0x53, 0x28, 0x5e, 0x3c, 0x05, 0xc1, 0x73, 0x3e, 0x9e, 0x31, 0xd8, 0x66,
	0xd3, 0xb7, 0x9b, 0xc5, 0xfc, 0x1f, 0x7f, 0xa4, 0x47, 0xd9, 0x5d, 0x82, 0x8b, 0x12, 0x6f, 0xf3,
	0x26, 0x33, 0xf3, 0x32, 0xfb, 0xc8, 0x8d, 0x44, 0xcd, 0x11, 0x72, 0x81, 0x05, 0x20, 0x6f, 0x50,
	0x28, 0xf1, 0x33, 0xf6, 0x80, 0x59, 0x9e, 0x86, 0xfd, 0x2c, 0x51, 0x47, 0x17, 0xa5, 0x10, 0xe5,
	0x0e, 0x9c, 0x25, 0x6b, 0x5f, 0x39, 0xec, 0x1b, 0xd5, 0x39, 0x65, 0x74, 0x5f, 0x56, 0xea, 0xad,
	0xcd, 0x58, 0x2e, 0xf6, 0x1c, 0x6a, 0x2d, 0xba, 0x06, 0xc5, 0x47, 0xe7, 0xb4, 0xf9, 0xaa, 0x84,
	0x7a, 0xa5, 0xd3, 0x5d, 0x55, 0xa4, 0x0a, 0xf8, 0x1f, 0xe0, 0x22, 0x62, 0x4e, 0x66, 0xcf, 0x98,
	0xd6, 0x32, 0xcd, 0x55, 0x25, 0xea, 0x04, 0xd2, 0x22, 0x81, 0x43, 0x0b, 0x52, 0xd1, 0x29, 0x19,
	0xbf, 0x43, 0x37, 0x0f, 0x16, 0xc1, 0xf2, 0x34, 0x31, 0xf0, 0x6e, 0xfc, 0xf5, 0x10, 0xc4, 0x40,
	0xce, 0x3d, 0xc3, 0x0b, 0x56, 0x0a, 0x06, 0x1d, 0x74, 0x43, 0x26, 0xa0, 0xa1, 0x56, 0xf3, 0xa3,
	0x45, 0xb0, 0x0c, 0xd7, 0x97, 0xcc, 0xab, 0xc6, 0xbc, 0x98, 0xad, 0x11, 0x25, 0x4e, 0xeb, 0xd6,
	0xdc, 0x92, 0xe9, 0xef, 0xef, 0x26, 0x1f, 0xe1, 0x60, 0xf3, 0xcf, 0x12, 0x03, 0x2d, 0x23, 0x1b,
	0x9b, 0x6e, 0x18, 0xd9, 0xac, 0x3f, 0x03, 0x12, 0x7a, 0x46, 0xfa, 0x44, 0x8e, 0x4d, 0x29, 0x7a,
	0x35, 0xb4, 0xda, 0xab, 0x1c, 0xfd, 0xff, 0x7f, 0xf1, 0x88, 0x3e, 0x92, 0x89, 0x6d, 0x4c, 0xaf,
	0x87, 0x94, 0xfe, 0x83, 0x44, 0x33, 0xe6, 0xae, 0xc7, 0xfa, 0xeb, 0xb1, 0xad, 0xb9, 0x5e, 0x3c,
	0xca, 0x4e, 0x2c, 0xb3, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x54, 0x47, 0x89, 0x18, 0x02,
	0x00, 0x00,
}
