// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/recorder/proto/recorder/recorder.proto

package recordersrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Transaction Event
type TransactionEvent struct {
	// request
	Req []byte `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	// responce
	Rsp                  []byte   `protobuf:"bytes,2,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_65991f949dbc3f7a, []int{0}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *TransactionEvent) GetRsp() []byte {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionEvent)(nil), "recordersrv.TransactionEvent")
}

func init() {
	proto.RegisterFile("srv/recorder/proto/recorder/recorder.proto", fileDescriptor_65991f949dbc3f7a)
}

var fileDescriptor_65991f949dbc3f7a = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0x2e, 0x2a, 0xd3,
	0x2f, 0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0x49, 0x2d, 0xd2, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x47, 0x70,
	0x61, 0x0c, 0x3d, 0xb0, 0xb8, 0x10, 0x37, 0x8c, 0x5f, 0x5c, 0x54, 0xa6, 0x64, 0xc6, 0x25, 0x10,
	0x52, 0x94, 0x98, 0x57, 0x9c, 0x98, 0x5c, 0x92, 0x99, 0x9f, 0xe7, 0x5a, 0x96, 0x9a, 0x57, 0x22,
	0x24, 0xc0, 0xc5, 0x5c, 0x94, 0x5a, 0x28, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x62, 0x82,
	0x45, 0x8a, 0x0b, 0x24, 0x98, 0xa0, 0x22, 0xc5, 0x05, 0x49, 0x6c, 0x60, 0xb3, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x35, 0x77, 0x7f, 0x84, 0x79, 0x00, 0x00, 0x00,
}
