// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/recorder/proto/transaction/transaction.proto

package transaction

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_771ddc17730a5676, []int{0}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type WriteRequest struct {
	Key                  string            `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Event                *TransactionEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_771ddc17730a5676, []int{1}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteRequest) GetEvent() *TransactionEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

// Transaction Event
type TransactionEvent struct {
	// request
	Req []byte `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	// responce
	Rsp                  []byte   `protobuf:"bytes,2,opt,name=rsp,proto3" json:"rsp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_771ddc17730a5676, []int{2}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *TransactionEvent) GetRsp() []byte {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func init() {
	proto.RegisterType((*ReadRequest)(nil), "micro.recorder.v1.ReadRequest")
	proto.RegisterType((*WriteRequest)(nil), "micro.recorder.v1.WriteRequest")
	proto.RegisterType((*TransactionEvent)(nil), "micro.recorder.v1.TransactionEvent")
}

func init() {
	proto.RegisterFile("srv/recorder/proto/transaction/transaction.proto", fileDescriptor_771ddc17730a5676)
}

var fileDescriptor_771ddc17730a5676 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x25, 0xaf, 0xaf, 0x0f, 0xde, 0xb4, 0x8b, 0xbe, 0x59, 0x3c, 0x4a, 0x04, 0x2d, 0xd5, 0x45,
	0x5d, 0x74, 0x46, 0x2b, 0x08, 0xba, 0x92, 0x4a, 0x57, 0x6e, 0x24, 0x0a, 0x42, 0x37, 0x3a, 0x4d,
	0xae, 0xe9, 0xd0, 0x26, 0x93, 0xde, 0xdc, 0x06, 0xfb, 0x3d, 0xfe, 0xa4, 0x4b, 0x99, 0x89, 0xd5,
	0x60, 0xab, 0xb8, 0x3b, 0xdc, 0x7b, 0x0e, 0xe7, 0x9e, 0x39, 0xc3, 0x8e, 0x72, 0x2c, 0x24, 0x42,
	0x68, 0x30, 0x02, 0x94, 0x19, 0x1a, 0x32, 0x92, 0x50, 0xa5, 0xb9, 0x0a, 0x49, 0x9b, 0xb4, 0x8a,
	0x85, 0xdb, 0xf2, 0x7f, 0x89, 0x0e, 0xd1, 0x88, 0xb5, 0x46, 0x14, 0xc7, 0xfe, 0x4e, 0x6c, 0x4c,
	0x3c, 0x87, 0x52, 0x3e, 0x59, 0x3e, 0x4a, 0x48, 0x32, 0x5a, 0x95, 0x7c, 0xff, 0x90, 0xa6, 0x1a,
	0xa3, 0xfb, 0x4c, 0x21, 0xad, 0xde, 0x0c, 0x0a, 0x35, 0xd7, 0x91, 0x22, 0x78, 0x07, 0x25, 0xb5,
	0x7b, 0xc0, 0x1a, 0x01, 0xa8, 0x28, 0x80, 0xc5, 0x12, 0x72, 0xe2, 0x2d, 0x56, 0x9b, 0xc1, 0xaa,
	0xed, 0x75, 0xbc, 0xde, 0xdf, 0xc0, 0xc2, 0xf3, 0xda, 0xcb, 0xd0, 0xeb, 0x3e, 0xb0, 0xe6, 0x1d,
	0x6a, 0x82, 0x2f, 0x69, 0xfc, 0x8c, 0xd5, 0xa1, 0x80, 0x94, 0xda, 0xbf, 0x3a, 0x5e, 0xaf, 0x31,
	0xd8, 0x17, 0x1b, 0x27, 0x8b, 0xdb, 0x8f, 0x5c, 0x23, 0x4b, 0x0d, 0x4a, 0x45, 0xe9, 0x70, 0xca,
	0x5a, 0x9f, 0xf7, 0xd6, 0x05, 0x61, 0xe1, 0x5c, 0x9a, 0x81, 0x85, 0x6e, 0x92, 0x67, 0xce, 0xc3,
	0x4e, 0xf2, 0x6c, 0xf0, 0xec, 0x31, 0x5e, 0x11, 0xde, 0x00, 0x16, 0x3a, 0x04, 0x7e, 0xc5, 0x7e,
	0xdb, 0x58, 0x7c, 0x77, 0xcb, 0x1d, 0x95, 0xbc, 0xfe, 0x4f, 0xee, 0xe4, 0x17, 0xac, 0xee, 0xd2,
	0xf3, 0xbd, 0x2d, 0xec, 0xea, 0xbb, 0xf8, 0xff, 0x45, 0x59, 0x8b, 0x58, 0xd7, 0x22, 0x46, 0xb6,
	0x96, 0xe1, 0x98, 0x6d, 0x56, 0x78, 0xed, 0x8d, 0x2f, 0x63, 0x4d, 0xd3, 0xe5, 0x44, 0x84, 0x26,
	0x91, 0x4f, 0xc9, 0x7c, 0xa6, 0xd3, 0x58, 0x3a, 0x5e, 0x3f, 0x27, 0x85, 0x04, 0xd8, 0x9f, 0x69,
	0x92, 0xdf, 0x7f, 0x97, 0xc9, 0x1f, 0x37, 0x3a, 0x79, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x25,
	0x79, 0x21, 0x57, 0x02, 0x00, 0x00,
}
