// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/account/proto/account/account.proto

package go_micro_srv_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Account_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Account_PingPongService, error)
}

type accountService struct {
	c    client.Client
	name string
}

func NewAccountService(name string, c client.Client) AccountService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.account"
	}
	return &accountService{
		c:    c,
		name: name,
	}
}

func (c *accountService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Account.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Account_StreamService, error) {
	req := c.c.NewRequest(c.name, "Account.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &accountServiceStream{stream}, nil
}

type Account_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type accountServiceStream struct {
	stream client.Stream
}

func (x *accountServiceStream) Close() error {
	return x.stream.Close()
}

func (x *accountServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountService) PingPong(ctx context.Context, opts ...client.CallOption) (Account_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Account.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &accountServicePingPong{stream}, nil
}

type Account_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type accountServicePingPong struct {
	stream client.Stream
}

func (x *accountServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *accountServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *accountServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Account service

type AccountHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Account_StreamStream) error
	PingPong(context.Context, Account_PingPongStream) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) error {
	type account interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Account struct {
		account
	}
	h := &accountHandler{hdlr}
	return s.Handle(s.NewHandler(&Account{h}, opts...))
}

type accountHandler struct {
	AccountHandler
}

func (h *accountHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.AccountHandler.Call(ctx, in, out)
}

func (h *accountHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AccountHandler.Stream(ctx, m, &accountStreamStream{stream})
}

type Account_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type accountStreamStream struct {
	stream server.Stream
}

func (x *accountStreamStream) Close() error {
	return x.stream.Close()
}

func (x *accountStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *accountHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.AccountHandler.PingPong(ctx, &accountPingPongStream{stream})
}

type Account_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type accountPingPongStream struct {
	stream server.Stream
}

func (x *accountPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *accountPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *accountPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *accountPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *accountPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
